# -*- coding: utf-8 -*-
"""Copy of convolutional_neural_network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-a96GScFP-q4tzTFeTFjZWK36KbPAGe

# Convolutional Neural Network

### Importing the libraries

## Part 1 - Data Preprocessing

### Preprocessing the Training set
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

"""### Preprocessing the Test set

## Part 2 - Building the CNN

### Initialising the CNN

### Step 1 - Convolution

### Step 2 - Pooling

### Adding a second convolutional layer

### Step 3 - Flattening

### Step 4 - Full Connection

### Step 5 - Output Layer

## Part 3 - Training the CNN

### Compiling the CNN

### Training the CNN on the Training set and evaluating it on the Test set

## Part 4 - Making a single prediction
"""