# -*- coding: utf-8 -*-
"""Copy of random_forest_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJedJbghKggdwl9jflSiDIELduN9C3Mj

# Random Forest Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

"""## Training the Random Forest Regression model on the whole dataset

## Predicting a new result

## Visualising the Random Forest Regression results (higher resolution)
"""