# -*- coding: utf-8 -*-
"""Copy of logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wY6E6b_B0EgEU_JPinxt4LWVy1w4n5NZ

# Logistic Regression

## Importing the libraries

## Importing the dataset

## Splitting the dataset into the Training set and Test set

## Feature Scaling

## Training the Logistic Regression model on the Training set

## Predicting a new result

## Predicting the Test set results

## Making the Confusion Matrix

## Visualising the Training set results

## Visualising the Test set results
"""